spring:
  application:
    name: menu-server
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    
eureka:
  client:
    service-url:
     defaultzone: http://localhost:8282/eureka
           
server:
  port: 8181
