spring:
  application:
    name: menu-service
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
server:
  port: 8181
